# Change these first
owner: idirecto # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Idirecto
    url: https://idirecto.es
  - name: Puntobyze
    url: https://puntobyze.com
  - name: Api Idirecto
    url: https://api.idirecto.es
  - name: Api Amazon
    url: https://amazon.idirecto.es/
    
assignees:
  - idirecto
  - palisick

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Idirecto Status
  introTitle: "Status de Idirecto/Puntobyze"
  introMessage: Página creada con el repositorio https://github.com/upptime/upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
